# Generated by Django 2.1 on 2018-08-20 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divison', models.CharField(choices=[('dha', 'Dhaka'), ('Cht', 'Chittagong'), ('raj', 'Rajshai'), ('bri', 'Barishal'), ('khu', 'Khulna'), ('syh', 'Sylhet'), ('ran', 'Rangpur'), ('mym', 'Mymensingh')], max_length=10, verbose_name='Divisions')),
                ('district', models.CharField(choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15, verbose_name='Districts')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10 digit mobile', regex='^[6-9]\\d{9}$')], verbose_name='Phone -')),
                ('address', models.TextField(verbose_name='Address')),
                ('commodities', models.TextField(verbose_name='What you can contributor. (..)')),
                ('status', models.CharField(choices=[('new', 'New'), ('ful', 'Fullfilled')], default='new', max_length=10)),
            ],
            options={
                'verbose_name': 'Contributor:Donation',
                'verbose_name_plural': 'Contributors:Donations',
            },
        ),
    ]
