# Generated by Django 2.1 on 2018-08-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0002_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15)),
                ('collection', models.TextField(verbose_name='Details of collected items')),
            ],
            options={
                'verbose_name': 'District: collection',
                'verbose_name_plural': 'Districts: collections',
            },
        ),
        migrations.CreateModel(
            name='DistrictManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15, verbose_name='Districts')),
                ('name', models.CharField(max_length=100, verbose_name='Name -')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'District: Manager',
                'verbose_name_plural': 'Districts: Managers',
            },
        ),
        migrations.CreateModel(
            name='DistrictNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15)),
                ('needs', models.TextField(verbose_name='Item required')),
                ('cnandpts', models.TextField(verbose_name='Contacts and collection points')),
            ],
            options={
                'verbose_name': 'District: Need',
                'verbose_name_plural': 'Districts: Needs',
            },
        ),
    ]
