# Generated by Django 2.1 on 2018-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0005_announcements_reliefcampdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRescueCamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Camp Name')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('district', models.CharField(choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15)),
                ('lsg_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='lsg name')),
                ('ward_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ward')),
                ('contacts', models.TextField(blank=True, null=True, verbose_name='Phone number')),
                ('facilities_available', models.TextField(blank=True, null=True, verbose_name='Facilities Available')),
                ('map_link', models.CharField(blank=True, help_text='Copy and paste the full link', max_length=250, null=True, verbose_name='Map link')),
                ('latlng', models.CharField(blank=True, help_text='Comma separated latlng field', max_length=100, verbose_name='GPS Coordinates')),
                ('total_people', models.IntegerField(blank=True, null=True, verbose_name='Total number of people')),
                ('total_males', models.IntegerField(blank=True, null=True, verbose_name='Total number of Males')),
                ('total_females', models.IntegerField(blank=True, null=True, verbose_name='Total number of Females')),
                ('total_infants', models.IntegerField(blank=True, null=True, verbose_name='Total number of infants <2y')),
                ('food_req', models.TextField(blank=True, null=True, verbose_name='Food requird')),
                ('clothing_req', models.TextField(blank=True, null=True, verbose_name='Cloth requird')),
                ('sanitry_req', models.TextField(blank=True, null=True, verbose_name='sanitary required')),
                ('medical_req', models.TextField(blank=True, null=True, verbose_name='medicine required')),
                ('other_req', models.TextField(blank=True, null=True, verbose_name='Others required')),
                ('status', models.CharField(choices=[('active', 'Activate'), ('closed', 'Closed')], default='active', max_length=10)),
            ],
            options={
                'verbose_name': 'Private Relief: Camp',
                'verbose_name_plural': 'Private Relief Camp: Camps',
            },
        ),
        migrations.RenameField(
            model_name='contributor',
            old_name='divison',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='rescuecamp',
            old_name='sanity_req',
            new_name='sanitry_req',
        ),
    ]
