# Generated by Django 2.1 on 2018-08-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0006_auto_20180829_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='detailkt_utils',
            new_name='detailkit_utils',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='needfooed',
            new_name='needfood',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='needkit_util',
            new_name='needkit_utils',
        ),
    ]
