# Generated by Django 2.1 on 2018-08-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0007_auto_20180829_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('contacts', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contacts')),
                ('type_of_materials_collecting', models.TextField(blank=True, null=True, verbose_name='Type of materials collecting')),
                ('district', models.CharField(blank=True, choices=[('bar', 'Barguna'), ('bri', 'Barisal'), ('bhl', 'Bhola'), ('jhl', 'Jhalokati'), ('pat', 'Patuakhali'), ('pir', 'Pirojpur'), ('ban', 'Bandarban'), ('bhm', 'Brahmanbaria'), ('chd', 'Chandpur'), ('cht', 'Chittagong'), ('com', 'Comilla'), ('cox', "Cox's Bazar"), ('fen', 'Feni'), ('khg', 'Khagrachhari'), ('lkh', 'Lakshmipur'), ('nkh', 'Noakhali'), ('rgm', 'Rangamati'), ('dhk', 'Dhaka'), ('frd', 'Faridpur'), ('gaz', 'Gazipur'), ('gop', 'Gopalganj'), ('kis', 'Kishoreganj'), ('mad', 'Madaripur'), ('man', 'Manikganj'), ('mun', 'Munshiganj'), ('nar', 'Narayanganj'), ('nas', 'Narsingdi'), ('raj', 'Rajbari'), ('sha', 'Shariatpur'), ('tan', 'Tangail'), ('bag', 'Bagerhat'), ('chu', 'Chuadanga'), ('jes', 'Jessore'), ('jhe', 'Jhenaidah'), ('khu', 'Khulna'), ('kus', 'Kushtai'), ('mag', 'Magura'), ('meh', 'Meherpur'), ('nri', 'Narail'), ('sat', 'Satkhira'), ('jam', 'Jamalpur'), ('mym', 'Mymensingh')], max_length=15, null=True, verbose_name='center District')),
                ('lsg_type', models.SmallIntegerField(blank=True, choices=[(0, 'Corporation'), (1, 'Municipality'), (2, 'Gram Panchayath')], null=True, verbose_name='LSG Type')),
                ('lsg_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='LSG name')),
                ('ward_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ward')),
                ('is_inside_kerala', models.BooleanField(default=True, verbose_name='center inside Kerala')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='City')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('map_link', models.TextField(blank=True, help_text='Copy and paste the full link', null=True, verbose_name='Map Link')),
            ],
        ),
    ]
