# Generated by Django 2.1 on 2018-09-28 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refegue', '0008_collectioncenter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'Volunteer: NGO', 'verbose_name_plural': 'Volunteers: NGOs'},
        ),
        migrations.RemoveField(
            model_name='contributor',
            name='commodities',
        ),
        migrations.AddField(
            model_name='contributor',
            name='contrib_details',
            field=models.TextField(default='', verbose_name='Details of contribution Eg: 10 shirts'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='contribution_type',
            field=models.CharField(choices=[('food', 'Food'), ('med', 'Medicines'), ('shl', 'Shelter'), ('clt', 'Clothing'), ('sny', 'Sanitary materials'), ('oth', 'Others')], default='oth', max_length=3),
        ),
        migrations.AddField(
            model_name='ngo',
            name='website_url',
            field=models.CharField(default='', max_length=300, verbose_name='Enter your website link'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='has_consented',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='phone',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10 digits mobile number or landline as 0<std code><phone number>', regex='^((91|91|0)[\\-]{0, 1})?[456789]\\d{9}$')], verbose_name='Phone -'),
        ),
    ]
